const labels: Record<string, string> = {
  RUNNING: "수집·가상거래 실행 중",
  PAUSED: "가상거래 일시정지",
  JEV_ERROR: "판단 서버 연결 대기",
  JEV_UNAVAILABLE: "판단 서버 응답·인증 대기",
  DATA_ERROR: "데이터 오류",
  DATA_STALE: "오래된 데이터",
  RISK_HALTED: "손실 한도 도달",
  WAITING: "수집 대기",
  CONNECTING: "연결 중",
  CONNECTED: "연결됨",
  REST_FALLBACK: "REST 대체 수집",
  CREDENTIALS_MISSING: "시세 API 키 필요",
  WARMING_UP: "과거 데이터 준비 중",
  MARKET_CLOSED: "장 마감·휴장",
  REPLAY_IDLE: "리플레이 대기",
  HOLD: "관망",
  LONG: "매수 후보",
  SHORT: "공매도 후보",
  EXIT: "청산 후보",
  OK: "정상",
  INVALID_RESPONSE: "응답 검증 실패",
  strong_up: "강한 상승",
  up: "상승",
  neutral: "중립",
  down: "하락",
  strong_down: "강한 하락",
  TRENDING_UP: "상승 추세",
  TRENDING_DOWN: "하락 추세",
  RANGING: "횡보",
  HIGH_VOLATILITY: "고변동성",
  LOW_VOLATILITY: "저변동성",
  EXECUTED: "가상 체결",
  NO_CHANGE: "유지",
  EXPIRED: "신호 만료",
  MAX_POSITIONS: "포지션 한도",
  INVALID_SIZE: "주문 수량 미달",
  STOCK_SHORT_DISABLED: "국내 공매도 비활성",
  COST_FILTER: "예상 익절폭이 거래 비용보다 작음",
  COOLDOWN: "시간 청산 후 대기·장 마감 진입 제한",
  TIME_EXIT: "최대 보유 시간 청산",
  SESSION_EXIT: "장 마감 전 청산",
  STOP_LOSS: "손절",
  TAKE_PROFIT: "익절",
  BUY_AND_HOLD: "매수 후 보유",
  EMA9_ABOVE_EMA21: "EMA 상승 조건",
  EMA9_BELOW_EMA21: "EMA 청산 조건",
  RSI_OVERSOLD: "RSI 과매도",
  RSI_EXIT: "RSI 청산 조건",
  RSI_NO_SIGNAL: "RSI 관망",
  AVOID_THRESHOLD: "회피 확률 초과",
  REVERSAL_RISK: "반전 위험",
  SETUP_QUALITY: "셋업 품질 부족",
  CONFLICTING_SIGNALS: "상반된 신호",
  BELOW_THRESHOLD: "확률 기준 미달",
  JEV_LONG_SETUP: "Jev 상승 셋업",
  JEV_SHORT_SETUP: "Jev 하락 셋업",
  PENDING: "다음 봉 대기",
  poor: "나쁨",
  weak: "약함",
  average: "보통",
  good: "좋음",
  excellent: "매우 좋음",
  very_low: "매우 낮음",
  low: "낮음",
  medium: "보통",
  high: "높음",
  very_high: "매우 높음",
};
export const t = (value: string | null | undefined) =>
  value ? (labels[value] ?? value) : "—";
const names: Record<string, string> = {
  "005930": "삼성전자",
  "000660": "SK하이닉스",
  "069500": "KODEX 200",
  "229200": "KODEX 코스닥150",
  "BTC/KRW": "비트코인",
  "ETH/KRW": "이더리움",
};
export const assetName = (symbol: string) => names[symbol] ?? symbol;
export const strategies: [string, string][] = [
  ["jev", "Jev 전략"],
  ["buy_hold", "매수 후 보유"],
  ["ema", "EMA 교차"],
  ["rsi", "RSI 전략"],
];
